name: Test1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  build-windows:
#    runs-on: windows-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    # https://github.com/actions/virtual-environments/issues/2961#issuecomment-801337633
#    - uses: Vampire/setup-wsl@v1
#      with:
#        distribution: Ubuntu-18.04
#
#    - name: Test1
#      run: |
#        Write-Host "---1-----------"
#        & "C:\Program Files\Git\bin\bash.exe" test.bash
#        Write-Host "---2-----------"
#        sed -i 's/\r$//' test.bash
#        & "C:\Windows\System32\bash.exe" test.bash
#        Write-Host "---1-----------"
#        & where.exe sh
#        Write-Host "---2-----------"
#        & where.exe bash
#        Write-Host "---3-----------"
#        Get-Command sh

#  build-nix:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0 ]
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Test Date Millis
#      run: |
#        time date +%s%3N
#        echo "---1---------------------"
#        time perl -MTime::HiRes=time -e 'printf "%.9f\n", time'
#        echo "---2---------------------"
#        time sysctl kern.boottime
#        sleep 1
#        time sysctl kern.boottime
  # https://github.com/marketplace/actions/freebsd-vm
  testfreebsd:
    runs-on: macos-latest
#    runs-on: macos-11
    name: A job to run test FreeBSD
#    env:
#      MYTOKEN : ${{ secrets.MYTOKEN }}
#      MYTOKEN2: "value2"
    steps:
      - uses: actions/checkout@v2
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0.1.5
        with:
#          envs: 'MYTOKEN MYTOKEN2'
          usesh: true
          prepare: |
            pkg install -y curl
            pkg install -y wget
            pkg install -y bash
            pkg install -y gawk
          run: |
            set -x
            pwd
            ls -lah
            ls -l /
            whoami
            # env
            freebsd-version
            command -v bash
            command -v sh
            command -v curl
            command -v wget
            command -v fetch
            command -v awk
            command -v gawk
            bash --version  || true
            awk --version   || true
            gawk --version  || true
            curl --version  || true
            wget --version  || true