on:
  - "push"
#  - "pull_request"

# test job user

name: "Run tests"

jobs:
  nix:
    name: "Tests *nix"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, macos-13 ]
    steps:
      - name: "run tests"
        run: |
          echo "who:"
          who
          echo "whoami:"
          whoami
          echo "groups:"
          groups
          echo 'sudo whoami:'
          sudo whoami
          echo "OSTYPE: $OSTYPE"
          echo "DONE!"

  win:
    name: "Tests Win"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
    steps:
      - name: "run tests"
        run: |
          Write-Host "current user:"
          Write-Host $(whoami)
          Write-Host $Env:UserName
          Write-Host "which bash:"
          which bash
          & bash -e -c 'echo "who:"; who; echo "whoami:"; whoami; echo "groups:"; groups||true; echo "OSTYPE: $OSTYPE"; echo done'
          Write-Host "DONE!"
