name: Test1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test1
      run: |
        Write-Host "---1-----------"
        & where sh
        Write-Host "---2-----------"
        Get-Command sh